API/urls.py
from . import views
from django.urls import path


app_name = 'api'
urlpatterns = [
    path('inc/', views.IndexView.as_view(), name='inc'),
    path('inc/<int:inc_id>', views.DetailView.as_view(), name='inc_det'),
    path('inc/<int:inc_id>/approve-image', views.approve_image, name='inc_apr_img'),
    path('inc/<int:inc_id>/verify', views.verify, name='inc_verify'),
    path('inc/dt', views.IncidentalListJson.as_view(), name='inc_dt'),
    path('auth/', views.AuthView.as_view()),
    path('factory/<int:number>', views.factory)
]

Site/urls.py
from . import views
from django.urls import path, include

app_name = 'site'
urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('gallery', views.gallery, name='gallery'),
    path('contact', views.contact, name='contact'),
    path('report', views.report, name='report'),
    path('inc/', views.IncView.index, name='inc_index'),
    path('inc/<int:inc_id>', views.IncView.detail, name='inc_detail')
]

Snowgum/urls.py
"""Snowgum URL Configuration"""
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('Site.urls')),
    path('api/', include('API.urls')),
    path('login/', views.LoginView.as_view(template_name='auth/login.html'), name='login'),
    path('logout/', views.LogoutView.as_view(template_name='auth/logout.html', next_page='/'), name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Site/views.py
from API.models import Incidental
from django.views.decorators.http import require_http_methods
from django.shortcuts import render, get_object_or_404
from django.template import RequestContext

@require_http_methods(['GET'])
def index(request):
    return render(request, 'site/index.html')


@require_http_methods(['GET'])
def about(request):
    return render(request, 'site/about.html')


@require_http_methods(['GET'])
def gallery(request):
    return render(request, 'site/gallery.html')


@require_http_methods(['GET'])
def contact(request):
    return render(request, 'site/contact.html')


@require_http_methods(['GET'])
def report(request):
    return render(request, 'site/report.html')


class IncView:
    @require_http_methods(['GET'])
    def index(request):
        inc = Incidental.objects.all()
        return render(request, 'site/inc/index.html', {'data': inc})

    @require_http_methods(['GET'])
    def detail(request, inc_id):
        inc = get_object_or_404(Incidental, pk=inc_id)
        return render(request, 'site/inc/detail.html', {'data': inc})

templates/site/inc/detail.html
{% extends "includes/base.html" %}
{% load static %}
{% block title %}Inc #{{ data.id }} | Snowgum Dieback{% endblock %}
{% block meta %}
    {% if user.is_authenticated %}
        <meta name="api-endpoint-apr-img" content="{% url 'api:inc_apr_img' data.id %}"/>
        <meta name="api-endpoint-verify" content="{% url 'api:inc_verify' data.id %}"/>
    {% endif %}
{% endblock %}
{% block content %}
<div class="row">
    <div class="col-sm-6">

            {% if user.is_authenticated %}
                <div class="alert alert-info">
                    <strong>Admin Actions</strong>
                    {% csrf_token %}
                    <div>
                        <button class="btn btn-sm btn-primary" id="btn-verify">
                            <span class="spinner-border spinner-border-sm d-none" role="status" aria-hidden="true"></span>
                            {% if data.verified %}
                                Un-verify
                            {% else %}
                                Verify
                            {% endif %}
                        </button>
                        <button class="btn btn-sm btn-success" id="btn-apr-img">
                            <span class="spinner-border spinner-border-sm d-none" role="status" aria-hidden="true"></span>
                            {% if data.image_apr %}
                                Un-approve Image
                            {% else %}
                                Approve Image
                            {% endif %}
                        </button>
                    </div>
                </div>
            {% endif%}

        <div class="card">
            <div class="card-header d-flex justify-content-between align-items-center">
                <h5 class="m-0 d-sm-flex align-items-center">
                    Observation #{{ data.id }}
                    {% if data.verified %}
                        <span class="ml-1 badge badge-success" id="verified-badge">Verified</span>
                    {% else %}
                        <span class="ml-1 badge badge-warning" id="verified-badge">Unverified</span>
                    {% endif %}
                </h5>
            </div>
            <div class="card-body">
                <p><strong>Date Observed: </strong>{{ data.date_obs|date:"D d/m/y" }}</p>
                <p><strong>Submitted: </strong>{{ data.ts_entered|date:"g:iA d/m/y" }}</p>
                {% if data.description %}
                    <p><strong>Description: </strong> {{ data.description }}</p>
                {% endif %}
                {% if user.is_authenticated %}
                    {% if data.email %}
                        <p><strong>Email: </strong>{{ data.email }} (contact: {{ data.contact }})</p>
                    {% endif %}
                {% endif %}
                <p><strong>Location: </strong>{{ data.loc_lat }}, {{ data.loc_lng }}</p>
                <div id="detail-map" data-lat="{{ data.loc_lat }}" data-lng="{{ data.loc_lng }}"></div>
            </div>
        </div>
    </div>
    <div class="col-sm-6 mt-2 mt-sm-0">
    {% if data.image %}
        {% if data.image_apr %}
            <img src="{{ MEDIA_URL }}{{ data.image }}" class="img-fluid img-thumbnail img-resize" alt="Image of tree"/>
        {% else %}
            {% if user.is_authenticated %}
                <div class="alert alert-warning">
                    <p class="mb-0">Please approve this image for public display.</p>
                </div>
                <img src="{{ MEDIA_URL }}{{ data.image }}" class="img-fluid img-thumbnail img-resize" alt="Image of tree"/>
            {% else %}
                <div class="alert alert-info">
                    <p class="mb-0">Image is awaiting approval.</p>
                </div>
            {% endif %}
        {% endif %}
    {% endif %}
    </div>
</div>
{% endblock %}

{% block scripts %}
    <script src="{% static 'js/detail.js' %}" type="application/javascript"></script>
    <script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBWtjXWbdncfXHq3RdeWGSn68eVlmR-wf8&callback=initMap">
    </script>
    {% if user.is_authenticated %}
        <script src="{% static 'js/detail-admin.js' %}" type="application/javascript"></script>
    {% endif %}
{% endblock %}

templates/site/inc/index.html
{% extends "includes/base.html" %}

{% block meta %}
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.20/datatables.min.css"/>
{% endblock %}
{% block title %}Data | Snowgum Dieback{% endblock %}
{% block content %}
    <div class="row">
        <div class="col">
            <h5>Datatable</h5>
            <table id="inc_table" class="table table-bordered table-sm table-responsive-sm" style="width:100%">
                <thead>
                    <tr>
                        <th>ID/Link</th>
                        <th>Date</th>
                        <th>Latitude</th>
                        <th>Longitude</th>
                        <th>Verified</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <h5>Heat Map</h5>
            <div id="heatmap" class="map"></div>
        </div>
        <div class="col-sm-6">
            <h5>Marker Map</h5>
            <div id="markermap" class="map"></div>
        </div>
    </div>

{% endblock %}

{% block scripts %}
<script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.20/datatables.min.js"></script>
<script>
    $(document).ready(function() {
        $('#inc_table').DataTable({
            "deferRender": true,
            "processing": true,
            "serverSide": true,
            "ajax": "{% url 'api:inc_dt' %}",
            columnDefs: [{
                targets: 0, //<-- index of column that should be rendered as link
                render : function(data, type, row, meta){
                    if (type === 'display'){
                        return $('<a>')
                            .attr('href', data)
                             .text("View #" + data)
                             .wrap('<div></div>')
                             .parent()
                             .html();
                    } else {
                        return data;
                    }
                }
            }]
        });
    });

    var heatMap, heatMapLayer, markerMap;
    function initMaps() {
        heatMap = new google.maps.Map(document.getElementById('heatmap'), {
            zoom: 5,
            center: {lat: -36.147610, lng: 148.486672},
            mapTypeControl: true,
            mapTypeId: 'terrain'
        });
        heatMapLayer = new google.maps.visualization.HeatmapLayer({
           data: getPointsForHeatMap(),
           map: heatMap
        });
        markerMap = new google.maps.Map(document.getElementById('markermap'), {
            zoom: 5,
            center: {lat: -36.147610, lng: 148.486672},
            mapTypeId: 'satellite',
            mapTypeControl: true
        });
        var infoWindow = new google.maps.InfoWindow({
           content: 'test'
        });
        {% for inc in data %}
            var marker{{ inc.id }} = new google.maps.Marker({
                position: {lat: {{ inc.loc_lat }}, lng: {{ inc.loc_lng }}},
                map: markerMap,
                title: 'Observation {{ inc.id }}'
            });
            marker{{ inc.id }}.addListener('click', function() {
                infoWindow.setContent(
                    '<p class="m-0"><strong>Observation #{{ inc.id }}</strong></p>' +
                    '<p class="m-0">{{ inc.date_obs }}</p>' +
                    '<a href={% url 'site:inc_detail' inc.id %}>View</a>'
                );
                infoWindow.open(markerMap, marker{{ inc.id }});
            });
        {% endfor %}
    }
    function getPointsForHeatMap() {
        return [
            {% for inc in data %}
            new google.maps.LatLng({{ inc.loc_lat }}, {{ inc.loc_lng }}),
            {% endfor %}
        ]
    }
</script>
<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBWtjXWbdncfXHq3RdeWGSn68eVlmR-wf8&libraries=visualization&callback=initMaps">
</script>
{% endblock %}