API/urls.py
from . import views
from django.urls import path


app_name = 'api'
urlpatterns = [
    path('inc/', views.IndexView.as_view(), name='inc'),
    path('inc/<int:inc_id>', views.DetailView.as_view(), name='inc_det'),
    path('inc/<int:inc_id>/approve-image', views.approve_image, name='inc_apr_img'),
    path('inc/<int:inc_id>/verify', views.verify, name='inc_verify'),
    path('inc/dt', views.IncidentalListJson.as_view(), name='inc_dt'),
    path('auth/', views.AuthView.as_view()),
    path('factory/<int:number>', views.factory)
]

Site/urls.py
from . import views
from django.urls import path, include

app_name = 'site'
urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('gallery', views.gallery, name='gallery'),
    path('contact', views.contact, name='contact'),
    path('report', views.report, name='report'),
    path('inc/', views.IncView.index, name='inc_index'),
    path('inc/<int:inc_id>', views.IncView.detail, name='inc_detail')
]

Snowgum/urls.py
"""Snowgum URL Configuration"""
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('Site.urls')),
    path('api/', include('API.urls')),
    path('login/', views.LoginView.as_view(template_name='auth/login.html'), name='login'),
    path('logout/', views.LogoutView.as_view(template_name='auth/logout.html', next_page='/'), name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Site/views.py
from API.models import Incidental
from django.views.decorators.http import require_http_methods
from django.shortcuts import render, get_object_or_404
from django.template import RequestContext

@require_http_methods(['GET'])
def index(request):
    return render(request, 'site/index.html')


@require_http_methods(['GET'])
def about(request):
    return render(request, 'site/about.html')


@require_http_methods(['GET'])
def gallery(request):
    return render(request, 'site/gallery.html')


@require_http_methods(['GET'])
def contact(request):
    return render(request, 'site/contact.html')


@require_http_methods(['GET'])
def report(request):
    return render(request, 'site/report.html')


class IncView:
    @require_http_methods(['GET'])
    def index(request):
        inc = Incidental.objects.all()
        return render(request, 'site/inc/index.html', {'data': inc})

    @require_http_methods(['GET'])
    def detail(request, inc_id):
        inc = get_object_or_404(Incidental, pk=inc_id)
        return render(request, 'site/inc/detail.html', {'data': inc})

templates/site/about.html
{% extends "includes/base.html" %}
{% load static %}
{% block title %}About | Snowgum Dieback{% endblock %}
{% block content %}
    <h3>About</h3>
    <div class="row">
        <div class="col">
            <figure class="figure float-right ml-2">
                <img src="{% static "img/examples/example2.jpg"%}" class="figure-img img-fluid rounded" width="400px"/>
                <figcaption class="figure-caption">Duis commodo tristique magna,</figcaption>
            </figure>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus eu nunc consequat, egestas est eu, finibus dui.
                Nullam posuere sodales vehicula. Aliquam egestas mi rhoncus congue cursus. Aenean porta hendrerit ultricies.
                Nullam finibus sapien mi, sed tempus nunc porta sed. Pellentesque eget bibendum quam. Sed feugiat ligula eget
                dui facilisis facilisis id vestibulum lacus. Duis commodo tristique magna, eu mollis enim elementum sit amet.
                Nam a ex placerat, interdum quam eu, tempus quam. Praesent pulvinar scelerisque mauris, in ornare sapien pretium
                nec. Pellentesque placerat volutpat metus ut ullamcorper. Praesent a dui vel ipsum congue sollicitudin et vel
                quam. Praesent ac nulla id orci iaculis luctus. Aenean sed posuere eros.
            </p>
            <p>
                Quisque id orci nec lectus porta ultrices. Proin et lacus lectus. Maecenas vel velit vitae nulla maximus
                consequat. Nam sed sapien non erat aliquam eleifend. Morbi in ultricies magna. Vestibulum hendrerit
                sodales justo. Morbi vitae odio pulvinar, hendrerit nisl ac, efficitur libero. Curabitur nisi elit,
                euismod eu dictum sed, pretium id dui. Donec vulputate, dolor vel gravida interdum, turpis nunc porttitor
                augue, sed ultricies tortor nisi et purus. Morbi tincidunt tincidunt massa, ut lacinia est mollis sit
                amet. Donec gravida lorem a ex viverra, eu posuere leo dignissim. Praesent porta mauris eros, elementum
                aliquam justo ultrices id. Donec commodo odio non tellus sodales egestas. Donec nec auctor mauris.
            </p>
            <figure class="figure float-right ml-2">
                <img src="{% static "img/examples/example3.jpg"%}" class="figure-img img-fluid rounded" width="400px"/>
                <figcaption class="figure-caption">Duis commodo tristique magna,</figcaption>
            </figure>
            <p>
                Praesent pharetra ac ante nec ultrices. Maecenas at lorem dui. Integer pulvinar nulla vel elit accumsan
                commodo. Suspendisse porta nisi eu purus tincidunt vehicula. Suspendisse quis vulputate nibh. Quisque
                imperdiet nunc at felis dignissim, sit amet tincidunt lectus ornare. Morbi at elit odio. Mauris sit amet
                sapien nec lorem convallis venenatis.
            </p>
        </div>
    </div>

{% endblock %}

templates/site/contact.html
{% extends "includes/base.html" %}
{% block title %}Contact | Snowgum Dieback{% endblock %}
{% block content %}

    <div class="row">
        <div class="col">
           <h3>Contact Us</h3>
            <address>
                <strong>Snowgum Dieback</strong><br>
                Fenner School of Environment and Society<br>
                Building 141<br>
                Linnaeus Way<br>
                Acton ACT 2601<br>
                <a href="#">contactemail@anu.edu.au</a>
            </address>
        </div>
    </div>
{% endblock %}

templates/site/gallery.html
{% extends "includes/base.html" %}
{% load static %}
{% block title %}Gallery | Snowgum Dieback{% endblock %}
{% block content %}
    <h3>Gallery</h3>
    <div class="row">
        <div class="col-sm-4">
            <img src="{% static "img/examples/example1.jpg"%}" alt="Example Image" class="img-thumbnail my-1"/>
            <img src="{% static "img/examples/example6.jpg"%}" alt="Example Image" class="img-thumbnail my-1"/>
        </div>
        <div class="col-sm-4">
            <img src="{% static "img/examples/example2.jpg"%}" alt="Example Image" class="img-thumbnail my-1"/>
            <img src="{% static "img/examples/example5.jpg"%}" alt="Example Image" class="img-thumbnail my-1"/>
        </div>
        <div class="col-sm-4">
            <img src="{% static "img/examples/example3.jpg"%}" alt="Example Image" class="img-thumbnail my-1"/>
            <img src="{% static "img/examples/example4.jpg"%}" alt="Example Image" class="img-thumbnail my-1"/>
        </div>

    </div>
{% endblock %}

templates/site/index.html
{% extends "includes/base.html" %}
{% load static %}
{% block content %}
    <div class="row">
        <div class="col-sm-10 offset-sm-1">
            <img src="{% static "img/banner.jpg" %}" alt="Banner" class="img-fluid"/>
        </div>
    </div>
    <div class="row mt-4">
        <div class="col-sm-8">
            <h5>Welcome to SnowgumDieback.com</h5>
            <p>Small blurb here</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque in libero et ipsum vehicula pharetra. In ut pulvinar erat, eu aliquet turpis. In at sollicitudin ipsum. Nulla vitae metus mi. Nunc vehicula volutpat sapien ut finibus. Integer volutpat arcu risus. Aenean a pharetra tortor. In commodo leo iaculis massa rhoncus suscipit. Ut et purus tristique, condimentum mauris aliquet, tristique justo.</p>
        </div>
        <div class="col-sm-4">
            <div class="card">
                <div class="card-header">
                    Quick links
                </div>
                <div class="card-body">
                    <ul>
                        <li><a href="{% url 'site:about' %}">About</a></li>
                        <li><a href="{% url 'site:inc_index' %}">Data</a></li>
                        <li><a href="{% url 'site:gallery' %}">Gallery</a></li>
                        <li><a href="{% url 'site:contact' %}">Contact</a></li>
                        <li><a href="{% url 'site:report' %}">Report</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/site/report.html
{% extends "includes/base.html" %}
{% load static %}
{% block meta %}
    <meta name="api-endpoint" content="{% url 'api:inc' %}"/>
{% endblock %}
{% block title %}Report | Snowgum Dieback{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-sm-6">
            <h3>Report Observation</h3>
            <p>If you have observed an occurrence of Snowgum Dieback, you are able to report it here and added to our research data.</p>
            <h5>Examples of Snowgum Dieback</h5>
            <div class="row">
                <div class="col-6 mb-2">
                    <a href="{% static "img/examples/example1.jpg" %}"><img src="{% static "img/examples/example1.jpg" %}" alt="Example 1" class="img-fluid img-thumbnail"/></a>
                </div>
                <div class="col-6">
                    <a href="{% static "img/examples/example5.jpg" %}"><img src="{% static "img/examples/example5.jpg" %}" alt="Example 1" class="img-fluid img-thumbnail"/></a>
                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <p>An image is required for verification and for the incidental to be added to the data.</p>
            <form id="reportForm">
                {% csrf_token %}
                <div class="form-group row mb-0">
                    <label for="form-photo" class="col-4 col-form-label"><strong>Upload image*</strong></label>
                    <div class="col-8">
                        <input id="form-photo" name="form-file" type="file" aria-describedby="form-fileHelpBlock" required="required" class="form-control-file" accept="image/jpeg, image/png">
                        <span id="form-photoHelpBlock" class="sr-only form-text text-muted">Upload a photo of the occurence</span>
                    </div>
                </div>
                <div class="form-group row mb-0">
                    <label for="form-date" class="col-4 col-form-label">Date</label>
                    <div class="col-8">
                        <input id="form-date" name="form-date" type="text" aria-describedby="form-dateHelpBlock" required="required" class="form-control-plaintext no-photo-disable" placeholder="yyyy-mm-dd">
                        <span id="form-dateHelpBlock" class="sr-only form-text text-muted">Enter the date you observed the occurrence</span>
                    </div>
                </div>
                <div class="form-group row mb-0 mt-3 d-none" id="location-search">
                    <label for="form-location" class="col-4 col-form-label">Location Search</label>
                    <div class="col-8">
                        <input id="form-location" name="form-location" type="text" class="form-control" aria-describedby="form-locationHelpBlock">
                        <span id="form-locationHelpBlock" class="sr-only form-text text-muted">Search for location to get GPS details</span>
                    </div>
                </div>
                <div class="form-group row mb-0">
                    <label for="form-lat" class="col-4 col-form-label">Latitude</label>
                    <div class="col-8">
                        <input id="form-lat" name="form-lat" type="number" disabled required="required" class="form-control-plaintext" placeholder="0.000000"/>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="form-lon" class="col-4 col-form-label">Longitude</label>
                    <div class="col-8">
                        <input id="form-lon" name="form-lon" type="number" disabled required="required" class="form-control-plaintext" placeholder="0.000000"/>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="form-description" class="col-4 col-form-label">Description</label>
                    <div class="col-8">
                        <textarea id="form-description" name="form-description" cols="40" rows="2" aria-describedby="form-descriptionHelpBlock" class="form-control no-photo-disable"></textarea>
                        <span id="form-descriptionHelpBlock" class="form-text text-muted">Enter any details about the observance</span>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="form-email" class="col-4 col-form-label">Email</label>
                    <div class="col-8">
                        <input id="form-email" placeholder="name@email.com" name="form-email" type="email" class="form-control no-photo-disable" aria-describedby="form-emailHelpBlock">
                        <span id="form-emailHelpBlock" class="form-text text-muted">If you would like to be contacted please provide your email address</span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="offset-4 col-8">
                        <div class="custom-control custom-checkbox custom-control-inline">
                            <input name="form-agree" id="form-agree" type="checkbox" class="custom-control-input no-photo-disable" value="false">
                            <label for="form-agree" class="custom-control-label">I agree to be contacted about this</label>
                        </div>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="offset-4 col-8">
                        <button name="submit" type="submit" id='form-submit' class="btn btn-primary no-photo-disable">
                            <span class="spinner-border spinner-border-sm d-none" role="status" aria-hidden="true"></span>
                            Submit
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>

{% endblock %}

{% block scripts %}
    <script src="{% static "js/jquery-ui.min.js" %}" type="application/javascript"></script>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBWtjXWbdncfXHq3RdeWGSn68eVlmR-wf8&libraries=places"></script>
    <script src="https://cdn.jsdelivr.net/npm/exif-js"></script>
    <script src="{% static "js/report.js" %}" type="application/javascript"></script>
{% endblock %}