API/urls.py
from . import views
from django.urls import path


app_name = 'api'
urlpatterns = [
    path('inc/', views.IndexView.as_view(), name='inc'),
    path('inc/<int:inc_id>', views.DetailView.as_view(), name='inc_det'),
    path('inc/<int:inc_id>/approve-image', views.approve_image, name='inc_apr_img'),
    path('inc/<int:inc_id>/verify', views.verify, name='inc_verify'),
    path('inc/dt', views.IncidentalListJson.as_view(), name='inc_dt'),
    path('auth/', views.AuthView.as_view()),
    path('factory/<int:number>', views.factory)
]

Site/urls.py
from . import views
from django.urls import path, include

app_name = 'site'
urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('gallery', views.gallery, name='gallery'),
    path('contact', views.contact, name='contact'),
    path('report', views.report, name='report'),
    path('inc/', views.IncView.index, name='inc_index'),
    path('inc/<int:inc_id>', views.IncView.detail, name='inc_detail')
]

Snowgum/urls.py
"""Snowgum URL Configuration"""
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('Site.urls')),
    path('api/', include('API.urls')),
    path('login/', views.LoginView.as_view(template_name='auth/login.html'), name='login'),
    path('logout/', views.LogoutView.as_view(template_name='auth/logout.html', next_page='/'), name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Snowgum Dieback{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/stylesheet.css" %}" type="text/css"/>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css" type="text/css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block meta %}{% endblock %}
</head>
<body>
    <div class="container-sm">
        {% comment %}Header{% endcomment %}
        <div class="row mt-2 mt-sm-4 justify-content-center">
            <div class="col-auto">
                <h1 class="d-none d-sm-block"><strong>Snowgum Dieback</strong></h1>
                <h2 class="d-sm-none"><strong>Snowgum Dieback</strong></h2>
            </div>
        </div>
        {% comment %}Nav{% endcomment %}
        <div class="row">
            <div class="col">
                <nav class="navbar navbar-expand-lg navbar-light bg-light">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapsedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarCollapsedContent">
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'site:index' %}">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'site:about' %}">About</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'site:inc_index' %}">Data</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'site:gallery' %}">Gallery</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'site:report' %}">Report</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'site:contact' %}">Contact</a>
                            </li>
                        </ul>
                        <ul class="navbar-nav">
                            {% if user.is_authenticated %}
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navUserDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Welcome {{ user.first_name }}
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navUserDropdown">
                                    <a class="dropdown-item" href="/admin">Admin Dashboard</a>
                                    <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                                </div>
                            </li>
                            {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'login' %}">Login</a>
                            </li>
                            {% endif %}
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
        {% comment %}Content{% endcomment %}
        <div class="row mt-3 mb-5">
            <div class="col">
                {% block content %}
                    <h3>Page Title</h3>
                    <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, commodo vitae, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. Donec non enim in turpis pulvinar facilisis. Ut felis. Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna eros eu erat. Aliquam erat volutpat. Nam dui mi, tincidunt quis, accumsan porttitor, facilisis luctus, metus</p>
                {% endblock %}
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
{% block scripts %}{% endblock %}
</body>
</html>